# Generated by Django 3.1.7 on 2021-03-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_departments_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=40)),
                ('Password', models.CharField(max_length=20)),
                ('ConfirmPassword', models.CharField(max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Departments_data',
        ),
    ]
